### ISSUE TITLE
nkn-mining Node Ubuntu 18.04. not starting

### ISSUE THREAD

**Issue by wichtigwicht** [nknorg/nkn-mining#1]
Hey there,

running a Ubuntu 18.04. VPS, the Application does not start via double klicking nknmining, nor starting it via Terminal.

Looking forward to giving more feedback!

**Comment by AKACoder** [comment]
fixed in release v0.0.2.

**Comment by AKACoder** [comment]
> Hey there,
> 
> running a Ubuntu 18.04. VPS, the Application does not start via double klicking nknmining, nor starting it via Terminal.
> 
> Looking forward to giving more feedback!

this issue was caused by systemd process manager, and was fixed in release v0.0.2.

**Comment by AKACoder** [comment]
@wichtigwicht this issue was caused by systemd process manager, and was fixed in release v0.0.2.
